[package]
name = "loxrs_env"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
loxrs_entities = {path = "../loxrs_entities"}
env_logger = "0.11.3"
log = "0.4.21"
