name: Formatting and linting

on: 
  push

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Run rustfmt
        run: cargo fmt -- --check
