name: Formatting and tests

on: 
  push

jobs:
  check-formatting-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Run rustfmt
        run: cargo fmt -- --check
      - name: Run tests
        run: cargo test -p loxrs_env
